### ISSUE TITLE
"Warning: a non-numeric value encountered"

### ISSUE THREAD

**Issue by chasinglucid** [aldolat/pinboard-bookmarks#4]
> Warning: A non-numeric value encountered in /home/techjenh/public_html/wp-includes/SimplePie/Parse/Date.php on line 694

This appears at the top of the results.

**Comment by aldolat** [comment]
I've never seen this warning before. Could you tell me the feed RSS address on Pinboard?

**Comment by aldolat** [comment]
This is due to the old version of SimplePie currently bundled with WordPress. The version 1.5 of SimplePie fixes this issue.

To resolve, change the line 694 of `/path/to/wordpress/wp-includes/SimplePie/Parse/Date.php` from this:

``` php
$second = round($match[6] + $match[7] / pow(10, strlen($match[7])));
```

into this:

``` php
$second = round((int)$match[6] + (int)$match[7] / pow(10, strlen($match[7])));
```

Until WordPress doesn't update SimplePie, you have to manually change this.
